### ISSUE TITLE
Vielä varmistus käytetystä frameworkista

### ISSUE THREAD

**Issue by RaimoGIS** [012843174/Raemae#1]
Eli, lähinnä testaamiselle on annettu jonkinlaista ohjeistusta kurssille ja tarkoituksena olisi käyttää Travisia ja easyb:tä. Travisilla voi testata Ruby koodia mutta easyb on tarkoitettu vain Javalle (easyb is a behavior driven development framework for the Java platform. )? Tässä vaiheessa olisi vielä hyvä lyödä varmuudella lukkoon ennen kuin varsinaista koodausta on tehty. Kurssin materiaaleissa olisi kaikki tarvittava testaamisen rakentamiseen mikäli käytämme Javaa.

En siis ala kapinoimaan jos mennään kuitenkin Rubylla, mutta jos muutoshalukkuutta vielä on niin kannattaisin kuitenkin Java/Spring setupia, koska siihen tuntuu olevan paras ohjeistus :).

**Comment by totutotu** [comment]
Joo, hyvä pointti.

Tutkin asiaa ja en oikein jaksaisi uskoa, että se easyB on se tän kurssin kuitenkaan olennaisin osuus? Oppimismatriisissa ei ainakaan mainintaa siitä ollenkaan. EasyB:n voima ilmeisesti on täysin siinä, että sillä pystyy kirjoittamaan User Storyt sellaisenaan koodiin, josta sitten on helppo lähteä laajentamaan automatisoiduksi koodiksi, mikä tietenkin on kiva homma, mutta sovelluksen "käyttäytymistä" voidaan ihan yhtä hyvin testata myös Rubyn rspec testeillä, joissa syntaksi on seuraavankaltaista:
---
describe "Places" do
 it "if one place is returned by the API, it is shown at the page" do
 allow(BeermappingApi).to receive(:places_in).with("kumpula").and_return(
 [ Place.new( name:"Oljenkorsi", id: 1 ) ]
 )
 visit places_path
 fill_in('city', with: 'kumpula')
 click_button "Search"
 expect(page).to have_content "Oljenkorsi"

 end
## ja loput metodit
-----
Eli ei siis tosiaan hirvean vaikeaa ainakaan ymmärtää (ainakaan omasta mielestäni), vaikkei koodin toimintaa oikein ymmärtäisikään.

Sanoisin että näillä mennään, seuraavassa asiakastapaamisessa viimeistään saadaan kommenttia, ollaanko sielä päässä tyytyväsiä tuotokseen, enkä usko, että tällä on juurikaan merkitystä.

Tuomo
On Tue, Apr 5, 2016 at 18:53, RaimoGIS  wrote:
	Eli, lähinnä testaamiselle on annettu jonkinlaista ohjeistusta kurssille ja tarkoituksena olisi käyttää Travisia ja easyb:tä. Travisilla voi testata Ruby koodia mutta easyb on tarkoitettu vain Javalle (easyb is a behavior driven development framework for the Java platform. )? Tässä vaiheessa olisi vielä hyvä lyödä varmuudella lukkoon ennen kuin varsinaista koodausta on tehty. Kurssin materiaaleissa olisi kaikki tarvittava testaamisen rakentamiseen mikäli käytämme Javaa. 

	En siis ala kapinoimaan jos mennään kuitenkin Rubylla, mutta jos muutoshalukkuutta vielä on niin kannattaisin kuitenkin Java/Spring setupia, koska siihen tuntuu olevan paras ohjeistus :).

**Comment by totutotu** [comment]
Niin! Ja pistäkääs skypet pystyyn, mut löytää siellä nimellä live:tuomo.torppa_2
On Tue, Apr 5, 2016 at 18:53, RaimoGIS  wrote:
	Eli, lähinnä testaamiselle on annettu jonkinlaista ohjeistusta kurssille ja tarkoituksena olisi käyttää Travisia ja easyb:tä. Travisilla voi testata Ruby koodia mutta easyb on tarkoitettu vain Javalle (easyb is a behavior driven development framework for the Java platform. )? Tässä vaiheessa olisi vielä hyvä lyödä varmuudella lukkoon ennen kuin varsinaista koodausta on tehty. Kurssin materiaaleissa olisi kaikki tarvittava testaamisen rakentamiseen mikäli käytämme Javaa. 

	En siis ala kapinoimaan jos mennään kuitenkin Rubylla, mutta jos muutoshalukkuutta vielä on niin kannattaisin kuitenkin Java/Spring setupia, koska siihen tuntuu olevan paras ohjeistus :).

**Comment by RaimoGIS** [comment]
Näillä mennään!

Mun Skype on rami.piiroinen@live.com

**Comment by RaimoGIS** [comment]
Näillä mennään!

Mun Skype nicki on ramipiiroinen

**Comment by nkoiv** [comment]
Skypessä "ayazha"
Laitan juuri issuetrackeriä meille pystyyn (google sheets) ja jaan sen heti kaikille kun valmista.
Pistäkää vaikka skypessä minulle gmailinne (tai mailinne yleensä) niin jaan teille, ettei suotta tule sähköpostiosoitteita tänne yleiseen jakoon.
