### ISSUE TITLE
Puuhatilitys

### ISSUE THREAD

**Issue by totutotu** [012843174/Raemae#2]
Perusvaatimukset tältä viikolta toimii ja pystyssä, nyt tehtävissä tälle viikolle vielä mielestäni:

-simppeli validointi (vaaditut kentät on required, mut ei) 
-testit
-vaadittu dokumentaatio

Backlogiin vinkkiä ja suuntaa oli materiaalissa täällä http://www.mountaingoatsoftware.com/agile/scrum/sprint-backlog , paha sanoa sitten kuinka paljon oikeasti pitää olla, mutta jotain tämänkaltaista ilmeisesti toivotaan.

Käytin itse öbaut kolme tuntia tähän tällä viikolla nyt tähän.

Pistäkään mulle herokussa tunnuksinanne olevat sähköpostit vielä niin lisään kaikki sinne, tulee haasteita jos ette pääse osallistumaan heroku-sovelluksen tekemiseen. 

travis.yml lisätty, en tosin saanut travisiä toimimaan? En oikein ymmärtänyt miten saada se käymään kun ei ole oma repo kyseessä.

**Comment by RaimoGIS** [comment]
Me käytettiin tämmöistä edellisessä projektissa ja oli aivan riittävä. Laitan mun google driveen ja jaan linkin

http://xaviesteve.com/1147/agile-scrum-google-spreadsheet-template-for-freelancers/
