### ISSUE TITLE
Sprint 1 TODO

### ISSUE THREAD

**Issue by nkoiv** [012843174/Raemae#3]
1. product backlog
 1. backlog on DEEP (storyjä ei tarvitse estimoida)

2. sprintin 1 backlog
 1. sprintiin valitut user storyt jaettu teknisen tason taskeiksi
 2. päivittäinen jäjellä oleva työmäärä arvioitu taskeittain
 3. burndown-käydä olemassa

3. sprintiin 1 valittujen storyjen hyväksymisehdot kirjattu

4. testaus
 1. kaikki toteutettu koodi melko kattavasti testattua
 2. yksikkötestit
 3. ainakin jossain storyssä hyväksymäehtojen testausta (easyB)

4. ~~jatkuva integraatio~~ (DONE)
 1. ~~koodi githubissa~~

5. definition of done kirjattu eksplisiittisesti

6. toteutus
 1. suurin osa sprintin tavoitteeseen sovituista storyistä toteutettu Definition of donen mukaisella tasolla työtä tehty tasaisesti

7. kaikki ei saa olla yhtenä päivänä tehty

8. toimiva, demossa näytettävä versio on tagatty (tagilla sprintti1) ja siitä on luotu GitHubiin release. Jos kyseessä on konsolisovellus, releaseen liitetään projektin ajettava jar-tiedosto

Tiketti-spreadsheet @ 
https://docs.google.com/spreadsheets/d/1UN19Phc53Km7Om7RmwkITS-FTbdp8SYZ4_RP2LQVMUw/edit?usp=sharing

**Comment by nkoiv** [comment]
Ekana listalla voisi olla se niiden korttien saaminen digitaaliseen muotoon (google docs?) ja niistä tuon product & sprint backlogin tekeminen. Ne voi sitten huoletta vetää yli... :)

**Comment by RaimoGIS** [comment]
https://docs.google.com/document/d/15qZsakg1xSxSVV7gekP1xkytX5nnsFUzYvnne71wP3Q/edit?usp=sharing

Tuolta löytyy kortin digitaalisesssa muodossa
